# Uncomment the next line to define a global platform for your project
  platform :ios, '13.4'

target 'Rover' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rover
  pod 'RealmSwift'

  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
